<?php

// Tipos de inmuebles
$listaTipo = array("Casas", "Dptos", "Oficinas", "Lotes", "Quintas");

// Lista de inmuebles
$listaInmuebles = array();

$listaInmuebles[] = array("id" => 1, "precio" => 450000, "direccion" => "Av. Beni", "telefono" => 12345678);
$listaInmuebles[] = array("direccion" => "Av. Santa Cruz", "precio" => 185000, "id" =>1,"telefono" => 456789);
$listaInmuebles[] = array("id" =>2, "direccion" => "Av. Banzer", "precio" => 45000, "telefono" => 10203040);
$listaInmuebles[] = array("id" =>3, "direccion" => "C/ 4", "precio" => 1000, "telefono" => 40302010);
$listaInmuebles[] = array("id" =>2, "direccion" => "Av. Moscú", "precio" => 62400, "telefono" => 12345678);

?>